context:
  version: "0.0.15"

package:
  name: pigweed
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/p/pigweed/pigweed-${{ version }}.tar.gz
  sha256: 46a4e78eeb83053a4a06c5caae0dbcdfc9bc656e5be054e9def3df619d895eca
  patches:
    - if: unix
      then: python_protos_unix.patch
    - if: win
      then: python_protos_win.patch

build:
  number: 0
  script: pip install . -v

requirements:
  host:
    - python >=3.10,<3.11
    - pip
    - setuptools
  run:
    - python_abi 3.10.* *_cp310
    - coloredlogs
    - cryptography
    - googleapis-common-protos >=1.56.2
    - ipython
    - jinja2
    - json5 >=0.9.10
    - prompt-toolkit >=3.0.26
    - protobuf >=3.20.1,<3.21
    - psutil
    - ptpython ==3.0.23
    - pyelftools
    - pygments
    - pyperclip
    - pyserial >=3.5,<4.0
    - pyyaml
    - requests
    - setuptools
    - six
    - watchdog >=2.1.0
    - websockets
    - wheel

tests:
  - python:
      imports:
        - pw_protobuf_compiler
        - pw_protobuf_compiler.python_protos
      pip_check: false

about:
  homepage: https://pigweed.dev/
  license: Apache-2.0
  summary: Pigweed is an open source collection of embedded-targeted libraries
  description: |
    Pigweed is an open source collection of embedded-targeted libraries, 
    or as we like to call them, modules. These modules are building blocks 
    and infrastructure that enable faster and more reliable development on 
    small-footprint MMU-less 32-bit microcontrollers like the STMicroelectronics 
    STM32L452 or the Nordic nRF52832.
