context:
  version: "0.11_be49612"
  # The specific commit or tag from your script
  download_url: "https://github.com/sparkmicro/dfu-util/releases/download/v0.11-be49612/dfu-util_be49612.zip"

package:
  name: dfu-util-spark
  version: ${{ version }}

source:
  url: ${{ download_url }}
  # It is good practice to add a sha256 checksum here so builds are reproducible
  sha256: "9a2961397839a9d5cb7091b60c2322933c27ffee308d26a03adfafa0887f21ba" 

build:
  number: 0
  script:
    - if: linux
      then: |
        mkdir -p $PREFIX/bin
        cp -r linux-amd64/* $PREFIX/bin/
    - if: win
      then: |
        mkdir %PREFIX%\\bin
        copy win64\\* %PREFIX%\\bin\\