#!/bin/bash
# Bootstrap script generated by Pixi VS Code Extension
# Downloads Pixi if missing and activates the environment

# Safe exit function (handles sourcing vs execution)
die() {
    echo "$1"
    # Check if sourced (Zsh vs Bash)
    if [[ -n "$ZSH_VERSION" ]]; then
       if [[ -o interactive ]]; then return 1; else exit 1; fi
    elif [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
        return 1
    else
        exit 1
    fi
}

# 1. Check for Pixi
if ! command -v pixi &> /dev/null; then
    if [ ! -f ".pixi/bin/pixi" ]; then
        echo "Pixi not found. Installing..."
        mkdir -p .pixi/bin
        
        # Detect OS/Arch
        OS="$(uname -s)"
        ARCH="$(uname -m)"
        
        URL=""
        if [ "$OS" = "Linux" ] && [ "$ARCH" = "x86_64" ]; then
            URL="https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz"
        elif [ "$OS" = "Darwin" ] && [ "$ARCH" = "arm64" ]; then
            URL="https://github.com/prefix-dev/pixi/releases/latest/download/pixi-aarch64-apple-darwin.tar.gz"
        elif [ "$OS" = "Darwin" ] && [ "$ARCH" = "x86_64" ]; then
             URL="https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-apple-darwin.tar.gz"
        else
            die "Unsupported platform for auto-bootstrap: $OS $ARCH"
        fi
        
        echo "Downloading $URL..."
        curl -L "$URL" -o pixi.tar.gz
        tar -xzf pixi.tar.gz -C .pixi/bin
        rm pixi.tar.gz
        chmod +x .pixi/bin/pixi
        echo "Pixi installed to .pixi/bin/pixi"
    fi
    export PATH="$PWD/.pixi/bin:$PATH"
fi

# 2. Activate
echo "Activating Pixi Environment..."
if [ -f "activate.sh" ]; then
    source activate.sh
else
    eval "$(pixi shell-hook)"
fi
