@echo off
setlocal EnableDelayedExpansion

REM Bootstrap script generated by Pixi VS Code Extension

set "BASE_URL=https://github.com/prefix-dev/pixi/releases/latest/download"
set "SCRIPT_DIR=%~dp0"
set "PIXI_DIR=%SCRIPT_DIR%.pixi\bin"
set "PIXI_BIN=%PIXI_DIR%\pixi.exe"
set "TARGET=x86_64-pc-windows-msvc"
set "ZIP_FILE=%SCRIPT_DIR%pixi.zip"

if not exist "%PIXI_BIN%" (
    echo Pixi not found.
    if not exist "%PIXI_DIR%" mkdir "%PIXI_DIR%"

    echo Downloading %BASE_URL%/pixi-%TARGET%.zip ...
    powershell -NoProfile -Command "$ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri '%BASE_URL%/pixi-%TARGET%.zip' -OutFile '%ZIP_FILE%'"
    
    if exist "%ZIP_FILE%" (
        echo Extracting...
        powershell -NoProfile -Command "Expand-Archive -Path '%ZIP_FILE%' -DestinationPath '%PIXI_DIR%' -Force"
        del "%ZIP_FILE%"
    ) else (
        echo Failed to download pixi.zip
        exit /b 1
    )
    
    if not exist "%PIXI_BIN%" (
        echo Checking for nested pixi.exe...
        for /r "%PIXI_DIR%" %%F in (pixi.exe) do (
            move /y "%%F" "%PIXI_BIN%"
        )
    )

    if not exist "%PIXI_BIN%" (
        echo Error: pixi.exe still not found.
        exit /b 1
    )
    
    echo Pixi installed.
)

endlocal

if exist "%SCRIPT_DIR%activate.bat" (
    call "%SCRIPT_DIR%activate.bat" %*
) else (
    echo activate.bat not found.
    exit /b 1
)
