context:
  name: ptpython
  version: 3.0.23

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/p/ptpython/ptpython-${{ version }}.tar.gz
  sha256: 9fc9bec2cc51bc4000c1224d8c56241ce8a406b3d49ec8dc266f78cd3cd04ba4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7
    - appdirs
    - importlib-metadata
    - jedi >=0.16.0
    - prompt-toolkit >=3.0.34,<3.1.0
    - pygments
