context:
  name: gcc-arm-none-eabi
  version: "10.3_2021.10"
  
package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # Linux (x86_64)
  - if: linux and x86_64
    then:
      url: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v10.3.1-2.3/xpack-arm-none-eabi-gcc-10.3.1-2.3-linux-x64.tar.gz
      sha256: 559dcf1c2dfddac513110fe23da0ef254032c09967eaa901f075515d51818719

  # Linux (AArch64)
  - if: linux and aarch64
    then:
      url: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v10.3.1-2.3/xpack-arm-none-eabi-gcc-10.3.1-2.3-linux-arm64.tar.gz
      sha256: 6e3ee605079ba084836cd057022e16c28605f4068042cd14397976b836ea1a21

  # macOS (x86_64)
  - if: osx
    then:
      url: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v10.3.1-2.3/xpack-arm-none-eabi-gcc-10.3.1-2.3-darwin-x64.tar.gz
      sha256: eb9218eaafb74a05fab9cbbeb49fd4fe7b85c6ba411aefc66f681a5a862e8d8e

  # Windows
  - if: win
    then:
      url: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v10.3.1-2.3/xpack-arm-none-eabi-gcc-10.3.1-2.3-win32-x64.zip
      sha256: 169744f784fb04ae10c60bc6a2cd69cff93cff0bf5657e9333776036f347f9c4

build:
  number: 0
  script: |
    # Enter directory if it exists (handles various packaging conventions)
    # If not found, we assume the files are in the current directory (which seems to be the case for xPack on Linux)
    if ls -d gcc-arm-none-eabi-* 1> /dev/null 2>&1; then
      cd gcc-arm-none-eabi-*
    elif ls -d arm-gnu-toolchain-* 1> /dev/null 2>&1; then
      cd arm-gnu-toolchain-*
    elif ls -d xpack-arm-none-eabi-gcc-* 1> /dev/null 2>&1; then
      cd xpack-arm-none-eabi-gcc-*
    fi

    # Create target directories
    mkdir -p $PREFIX/bin
    mkdir -p $PREFIX/lib
    mkdir -p $PREFIX/share
    mkdir -p $PREFIX/arm-none-eabi
    
    # Copy files
    cp -r bin/* $PREFIX/bin/
    cp -r lib/* $PREFIX/lib/
    cp -r share/* $PREFIX/share/
    cp -r arm-none-eabi/* $PREFIX/arm-none-eabi/
    
    # libexec is not always present in 10.3, but we check just in case
    if [ -d "libexec" ]; then
      mkdir -p $PREFIX/libexec
      cp -r libexec/* $PREFIX/libexec/
    fi

    # --- Symlink Patches (Linux Only) ---
    if [ "$(uname)" = "Linux" ]; then
        echo "Applying symlink patches for Linux..."
        
        # 1. Library Compatibility Fix
        # Create symlinks so binaries looking for .so.5 find the .so.6 provided by the environment
        cd $PREFIX/lib
        ln -sf libtinfo.so.6 libtinfo.so.5
        ln -sf libncurses.so.6 libncurses.so.5
        cd - > /dev/null

        # 2. GDB Symlink Fix (Pigweed override)
        # Force the bin/arm-none-eabi-gdb to point to the one inside the arm-none-eabi folder
        # if that is required by your specific tooling setup.
        ln -sf $PREFIX/arm-none-eabi/bin/arm-none-eabi-gdb $PREFIX/bin/arm-none-eabi-gdb
    fi

requirements:
  build:
    - make  # [unix]
  run:
    # Required for the symlink fix to work (provides libtinfo.so.6)
    - ncurses # [linux]