package:
  name: pyocd-packs
  version: "1.1.0"

source:
  - url: https://keilpack.azureedge.net/pack/Keil.STM32G4xx_DFP.2.2.0.pack
    sha256: "092a8700e79d65fd0d7ffe50e6140ce71e3162cecc0cbcf14db5714a086fcc00"
  - url: https://keilpack.azureedge.net/pack/Keil.STM32U5xx_DFP.3.2.0.pack
    sha256: "e320687fe534f2fe6902e9bcdee981315abea26c4ca547142af9b9439e958be6"
  - url: https://mcuxpresso.nxp.com/cmsis_pack/repo/NXP.LPC55S28_DFP.25.12.00.pack
    sha256: "bd043dc6900b515a4b57f086a84ce40af969e1b365c5414d1db32e1b611d5e3a"
  - path: .


build:
  number: 2
  noarch: generic
  script:
    - if: unix
      then: |
        mkdir -p $PREFIX/packs
        cp *.pack $PREFIX/packs/
        mkdir -p $PREFIX/etc/conda/activate.d
        cp activate.sh $PREFIX/etc/conda/activate.d/pyocd-packs-activate.sh
        cp update_pyocd.py $PREFIX/etc/conda/activate.d/update_pyocd.py
    - if: win
      then: |
        if not exist "%PREFIX%\\packs" mkdir "%PREFIX%\\packs"
        copy *.pack "%PREFIX%\\packs\\"
        if not exist "%PREFIX%\\etc\\conda\\activate.d" mkdir "%PREFIX%\\etc\\conda\\activate.d"
        copy activate.bat "%PREFIX%\\etc\\conda\\activate.d\\pyocd-packs-activate.bat"
        copy update_pyocd.py "%PREFIX%\\etc\\conda\\activate.d\\update_pyocd.py"

requirements:
  run:
    - python