context:
  name: qmk-driver-installer
  version: "1.0.0"
  # This is the official QMK driver installer release
  installer_url: "https://github.com/qmk/qmk_driver_installer/releases/download/v1.01/qmk_driver_installer.exe"
  # sha256 of the exe to ensure integrity (optional but recommended)
  sha256: "ccd78a40e3db74a189f42e3eab93463ef6c214c4f928b586992d70863b094431"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # 1. Download the installer executable
  - url: ${{ installer_url }}
    sha256: ${{ sha256 }}
  
  # 2. Include the local driver definition file
  # This expects 'qmk_drivers.txt' to be in the same folder as this recipe
  - path: qmk_drivers.txt

build:
  number: 2
  # This package is Windows-only
  skip: "not win"
  
  script: |
    mkdir "%PREFIX%\Library\driver_tools"
    
    if exist qmk_driver_installer.exe (
      copy qmk_driver_installer.exe "%PREFIX%\Library\driver_tools\"
    ) else (
      echo "Error: Installer executable not found in source"
      exit 1
    )

    copy qmk_drivers.txt "%PREFIX%\Library\driver_tools\"
    
    if not exist "%PREFIX%\Library\bin" mkdir "%PREFIX%\Library\bin"
    echo @echo off > "%PREFIX%\Library\bin\install-drivers.bat"
    
    echo powershell -Command "Start-Process '%PREFIX%\Library\driver_tools\qmk_driver_installer.exe' -ArgumentList '--force --all %PREFIX%\Library\driver_tools\qmk_drivers.txt' -WorkingDirectory '%PREFIX%\Library\driver_tools' -Verb RunAs" >> "%PREFIX%\Library\bin\install-drivers.bat"

requirements:
  build:
    # No compiler needed
  run:
    # No runtime dependencies